// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as BurbleSpatial from "../BurbleSpatial.res.mjs";

let state = {
  gameState: "InMenu",
  role: undefined,
  partnerPeerId: undefined,
  covertWhisperActive: false,
  autoMuted: false,
  onVoiceCommand: undefined
};

function setGameState(newState) {
  let prevState = state.gameState;
  state.gameState = newState;
  if (newState === "InCutscene") {
    state.autoMuted = true;
  } else if (prevState === "InCutscene") {
    state.autoMuted = false;
  }
  if (newState === "InStealth") {
    state.covertWhisperActive = true;
  } else {
    state.covertWhisperActive = false;
  }
}

function setRole(role) {
  state.role = role;
}

function setPartner(peerId) {
  state.partnerPeerId = peerId;
}

function onVoiceCommand(handler) {
  state.onVoiceCommand = handler;
}

function updateCharacterPosition(x, y, z) {
  BurbleSpatial.setListenerPosition({
    x: x,
    y: y,
    z: z
  });
}

function updatePartnerPosition(x, y, z) {
  let peerId = state.partnerPeerId;
  if (peerId !== undefined) {
    return BurbleSpatial.setPeerPosition(peerId, {
      x: x,
      y: y,
      z: z
    });
  }
}

function makeExtension() {
  return {
    name: "idaptik-voice",
    onConnect: _client => {
      state.gameState = "InMenu";
      state.covertWhisperActive = false;
      state.autoMuted = false;
    },
    onRoomJoin: (_client, _roomId) => {
      BurbleSpatial.configure(50.0, 2.0, 1.5, "inverse", undefined);
      BurbleSpatial.setEnabled(true);
    },
    onRoomLeave: _client => {
      state.gameState = "InMenu";
      BurbleSpatial.setEnabled(false);
    },
    onVoiceFrame: (_client, frame) => {
      if (state.autoMuted) {
        return Core__Array.make(frame.length, 0.0);
      }
    },
    onParticipantChange: (_client, participant) => {
      
    },
    onDisconnect: _client => {
      state.gameState = "InMenu";
      state.role = undefined;
      state.partnerPeerId = undefined;
    }
  };
}

export {
  state,
  setGameState,
  setRole,
  setPartner,
  onVoiceCommand,
  updateCharacterPosition,
  updatePartnerPosition,
  makeExtension,
}
/* BurbleSpatial Not a pure module */
