// Generated by ReScript, PLEASE EDIT WITH CARE


let state = {
  context: "GlobalHuddle",
  activeRoomId: undefined,
  speechToTextEnabled: false,
  recordingConsent: false,
  onPanelBusEvent: undefined,
  onVoiceTag: undefined
};

function setContext(ctx) {
  state.context = ctx;
}

function setSpeechToText(enabled) {
  state.speechToTextEnabled = enabled;
}

function setRecordingConsent(consent) {
  state.recordingConsent = consent;
}

function onPanelBusEvent(handler) {
  state.onPanelBusEvent = handler;
}

function onVoiceTag(handler) {
  state.onVoiceTag = handler;
}

function emitPanelBus(event) {
  let handler = state.onPanelBusEvent;
  if (handler !== undefined) {
    return handler(event);
  }
}

function emitVoiceTag(event) {
  let handler = state.onVoiceTag;
  if (handler !== undefined) {
    return handler(event);
  }
}

function makeExtension() {
  return {
    name: "panll-voice",
    onConnect: _client => {
      state.context = "GlobalHuddle";
      state.activeRoomId = undefined;
    },
    onRoomJoin: (_client, roomId) => {
      state.activeRoomId = roomId;
      emitPanelBus({
        TAG: "VoiceSessionStarted",
        panelContext: state.context,
        roomId: roomId
      });
    },
    onRoomLeave: _client => {
      emitPanelBus({
        TAG: "VoiceSessionEnded",
        panelContext: state.context
      });
      state.activeRoomId = undefined;
    },
    onVoiceFrame: undefined,
    onParticipantChange: (_client, participant) => {
      if (participant.isSpeaking) {
        return emitPanelBus({
          TAG: "SpeechStarted",
          userId: participant.id,
          displayName: participant.displayName
        });
      } else {
        return emitPanelBus({
          TAG: "SpeechEnded",
          userId: participant.id
        });
      }
    },
    onDisconnect: _client => {
      state.activeRoomId = undefined;
      emitPanelBus({
        TAG: "VoiceSessionEnded",
        panelContext: state.context
      });
    }
  };
}

export {
  state,
  setContext,
  setSpeechToText,
  setRecordingConsent,
  onPanelBusEvent,
  onVoiceTag,
  emitPanelBus,
  emitVoiceTag,
  makeExtension,
}
/* No side effect */
