// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Dict from "@rescript/core/src/Core__Dict.res.mjs";

function defaultState() {
  return {
    peerPositions: {},
    listenerPosition: {
      x: 0.0,
      y: 0.0,
      z: 0.0
    },
    listenerOrientation: {
      forwardX: 0.0,
      forwardY: 0.0,
      forwardZ: -1.0,
      upX: 0.0,
      upY: 1.0,
      upZ: 0.0
    },
    distanceModel: "inverse",
    maxDistance: 100.0,
    refDistance: 1.0,
    rolloffFactor: 1.0,
    enabled: true
  };
}

let state = defaultState();

function setPeerPosition(peerId, pos) {
  state.peerPositions[peerId] = pos;
}

function removePeer(peerId) {
  Core__Dict.$$delete(state.peerPositions, peerId);
}

function setListenerPosition(pos) {
  state.listenerPosition = pos;
}

function setListenerOrientation(orient) {
  state.listenerOrientation = orient;
}

function configure(maxDistanceOpt, refDistanceOpt, rolloffFactorOpt, distanceModelOpt, param) {
  let maxDistance = maxDistanceOpt !== undefined ? maxDistanceOpt : 100.0;
  let refDistance = refDistanceOpt !== undefined ? refDistanceOpt : 1.0;
  let rolloffFactor = rolloffFactorOpt !== undefined ? rolloffFactorOpt : 1.0;
  let distanceModel = distanceModelOpt !== undefined ? distanceModelOpt : "inverse";
  state.maxDistance = maxDistance;
  state.refDistance = refDistance;
  state.rolloffFactor = rolloffFactor;
  state.distanceModel = distanceModel;
}

function setEnabled(enabled) {
  state.enabled = enabled;
}

function distanceTo(peerId) {
  let peer = state.peerPositions[peerId];
  if (peer === undefined) {
    return;
  }
  let dx = peer.x - state.listenerPosition.x;
  let dy = peer.y - state.listenerPosition.y;
  let dz = peer.z - state.listenerPosition.z;
  return Math.sqrt(dx * dx + dy * dy + dz * dz);
}

function directionTo(peerId) {
  let peer = state.peerPositions[peerId];
  if (peer === undefined) {
    return;
  }
  let dx = peer.x - state.listenerPosition.x;
  let dy = peer.y - state.listenerPosition.y;
  let dz = peer.z - state.listenerPosition.z;
  let dist = Math.sqrt(dx * dx + dy * dy + dz * dz);
  if (dist > 0.001) {
    return {
      x: dx / dist,
      y: dy / dist,
      z: dz / dist
    };
  } else {
    return {
      x: 0.0,
      y: 0.0,
      z: 0.0
    };
  }
}

function makeExtension() {
  return {
    name: "burble-spatial",
    onConnect: _client => {
      state.enabled = true;
    },
    onRoomJoin: (_client, _roomId) => {
      state.peerPositions = {};
    },
    onRoomLeave: _client => {
      state.peerPositions = {};
      state.enabled = false;
    },
    onVoiceFrame: undefined,
    onParticipantChange: (_client, participant) => {
      if (participant.voiceState === "Deafened") {
        return removePeer(participant.id);
      }
    },
    onDisconnect: _client => {
      state.peerPositions = {};
      state.enabled = false;
    }
  };
}

export {
  defaultState,
  state,
  setPeerPosition,
  removePeer,
  setListenerPosition,
  setListenerOrientation,
  configure,
  setEnabled,
  distanceTo,
  directionTo,
  makeExtension,
}
/* state Not a pure module */
