// Generated by ReScript, PLEASE EDIT WITH CARE


function merge(base, overrides) {
  return overrides;
}

let gaming = {
  inputMode: {
    TAG: "PushToTalk",
    _0: "KeyV"
  },
  noiseSuppression: true,
  echoCancellation: false,
  spatialAudio: true,
  e2ee: false,
  targetLatencyMs: 20,
  bitrateKbps: 32
};

let workspace = {
  inputMode: "VoiceActivity",
  noiseSuppression: true,
  echoCancellation: true,
  spatialAudio: false,
  e2ee: true,
  targetLatencyMs: 40,
  bitrateKbps: 48
};

let broadcast = {
  inputMode: "VoiceActivity",
  noiseSuppression: true,
  echoCancellation: true,
  spatialAudio: false,
  e2ee: false,
  targetLatencyMs: 100,
  bitrateKbps: 96
};

let maxPrivacy = {
  inputMode: {
    TAG: "PushToTalk",
    _0: "Space"
  },
  noiseSuppression: true,
  echoCancellation: true,
  spatialAudio: false,
  e2ee: true,
  targetLatencyMs: 60,
  bitrateKbps: 32
};

export {
  gaming,
  workspace,
  broadcast,
  maxPrivacy,
  merge,
}
/* No side effect */
