// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Phoenix from "phoenix";

function make(serverUrl, callbacks) {
  return {
    socket: undefined,
    channel: undefined,
    connected: false,
    roomId: undefined,
    serverUrl: serverUrl,
    callbacks: callbacks
  };
}

function connect(state, token) {
  let socket = new Phoenix.Socket(state.serverUrl, {
    params: {
      token: token
    }
  });
  socket.connect();
  state.socket = socket;
  state.connected = true;
}

function connectGuest(state, displayName) {
  let socket = new Phoenix.Socket(state.serverUrl, {
    params: {
      guest: "true",
      display_name: displayName
    }
  });
  socket.connect();
  state.socket = socket;
  state.connected = true;
}

function disconnect(state) {
  let ch = state.channel;
  if (ch !== undefined) {
    ch.leave();
  }
  let s = state.socket;
  if (s !== undefined) {
    s.disconnect();
  }
  state.socket = undefined;
  state.channel = undefined;
  state.connected = false;
  state.roomId = undefined;
}

function joinRoom(state, roomId, displayName) {
  let socket = state.socket;
  if (socket === undefined) {
    return state.callbacks.onError("Not connected");
  }
  let topic = "room:" + roomId;
  let channel = socket.channel(topic, {
    display_name: displayName
  });
  channel.on("presence_state", payload => state.callbacks.onEvent({
    TAG: "PresenceState",
    _0: payload
  }));
  channel.on("voice_state_changed", payload => state.callbacks.onEvent({
    TAG: "VoiceStateChanged",
    userId: payload["user_id"],
    voiceState: payload["voice_state"]
  }));
  channel.on("signal", payload => state.callbacks.onEvent({
    TAG: "Signal",
    from: payload["from"],
    toSelf: payload["to"],
    signalType: payload["type"],
    payload: payload["payload"]
  }));
  channel.on("text", payload => state.callbacks.onEvent({
    TAG: "TextMessage",
    userId: payload["user_id"],
    displayName: payload["display_name"],
    body: payload["body"],
    sentAt: payload["sent_at"]
  }));
  let joinPush = channel.join();
  joinPush.receive("ok", resp => {
    state.roomId = roomId;
    state.callbacks.onJoined(resp);
  });
  joinPush.receive("error", resp => state.callbacks.onError("Join failed: " + JSON.stringify(resp)));
  state.channel = channel;
}

function leaveRoom(state) {
  let ch = state.channel;
  if (ch !== undefined) {
    ch.leave();
  }
  state.channel = undefined;
  state.roomId = undefined;
}

function sendVoiceState(state, voiceState) {
  let ch = state.channel;
  if (ch !== undefined) {
    ch.push("voice_state", {
      state: voiceState
    });
    return;
  }
}

function sendSignal(state, to, signalType, payload) {
  let ch = state.channel;
  if (ch !== undefined) {
    ch.push("signal", {
      to: to,
      type: signalType,
      payload: payload
    });
    return;
  }
}

function sendText(state, body) {
  let ch = state.channel;
  if (ch !== undefined) {
    ch.push("text", {
      body: body
    });
    return;
  }
}

function sendWhisper(state, to) {
  let ch = state.channel;
  if (ch !== undefined) {
    ch.push("whisper", {
      to: to
    });
    return;
  }
}

export {
  make,
  connect,
  connectGuest,
  disconnect,
  joinRoom,
  leaveRoom,
  sendVoiceState,
  sendSignal,
  sendText,
  sendWhisper,
}
/* phoenix Not a pure module */
