// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function make(profileConfig) {
  return {
    rtcState: "Idle",
    localStream: undefined,
    peerConnection: undefined,
    audioContext: undefined,
    isMuted: false,
    isDeafened: false,
    isSpeaking: false,
    audioLevel: 0.0,
    inputDevice: undefined,
    outputDevice: undefined,
    profileConfig: profileConfig
  };
}

async function acquireMicrophone(engine) {
  let constraints = {
    audio: {
      autoGainControl: true,
      noiseSuppression: engine.profileConfig.noiseSuppression,
      echoCancellation: engine.profileConfig.echoCancellation,
      channelCount: 1,
      sampleRate: 48000
    },
    video: false
  };
  try {
    let stream = await navigator.mediaDevices.getUserMedia(constraints);
    engine.localStream = stream;
    return {
      TAG: "Ok",
      _0: undefined
    };
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: Core__Option.getOr(Stdlib_JsExn.message(exn._1), "Microphone access denied")
      };
    } else {
      return {
        TAG: "Error",
        _0: "Microphone access denied"
      };
    }
  }
}

async function listDevices() {
  try {
    let devices = await navigator.mediaDevices.enumerateDevices();
    let audioDevices = Core__Array.filterMap(devices, d => {
      let kind = d["kind"];
      if (kind === "audioinput" || kind === "audiooutput") {
        return {
          deviceId: d["deviceId"],
          label: d["label"],
          kind: kind
        };
      }
    });
    return {
      TAG: "Ok",
      _0: audioDevices
    };
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: Core__Option.getOr(Stdlib_JsExn.message(exn._1), "Failed to enumerate devices")
      };
    } else {
      return {
        TAG: "Error",
        _0: "Failed to enumerate devices"
      };
    }
  }
}

function toggleMute(engine) {
  engine.isMuted = !engine.isMuted;
  let stream = engine.localStream;
  if (stream !== undefined) {
    let tracks = stream.getAudioTracks();
    tracks.forEach(track => {
      track.enabled = !engine.isMuted;
    });
  }
  return engine.isMuted;
}

function toggleDeafen(engine) {
  engine.isDeafened = !engine.isDeafened;
  if (engine.isDeafened && !engine.isMuted) {
    toggleMute(engine);
  }
  return engine.isDeafened;
}

function setInputDevice(engine, deviceId) {
  engine.inputDevice = deviceId;
}

function setOutputDevice(engine, deviceId) {
  engine.outputDevice = deviceId;
}

function destroy(engine) {
  let stream = engine.localStream;
  if (stream !== undefined) {
    let tracks = stream.getTracks();
    tracks.forEach(track => {
      track.stop();
    });
  }
  let pc = engine.peerConnection;
  if (pc !== undefined) {
    pc.close();
  }
  let ctx = engine.audioContext;
  if (ctx !== undefined) {
    ctx.close();
  }
  engine.localStream = undefined;
  engine.peerConnection = undefined;
  engine.audioContext = undefined;
  engine.rtcState = "Closed";
}

export {
  make,
  acquireMicrophone,
  listDevices,
  toggleMute,
  toggleDeafen,
  setInputDevice,
  setOutputDevice,
  destroy,
}
/* Stdlib_JsExn Not a pure module */
